name: Build and upload

on:
  pull_request: {}
  push:
    branches:
      - '*'
    tags:
      - '*'

# Must set Settings -> Actions -> General -> Workflow permissions to
# "Read and write permissions"
permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64, armhf]
        os: [16.04, 20.04, ut24.04-1.x]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Build
        env:
          ARCH: ${{ matrix.arch }}
          OS: ${{ matrix.os }}
        run: |
          docker build . --build-arg ARCH=$ARCH --build-arg UT_VERSION=$OS -t utsdl-$ARCH-$OS
          docker run --rm utsdl-$ARCH-$OS > utsdl-$ARCH-$OS.tgz

      - name: Upload CI build
        uses: actions/upload-artifact@v4
        with:
          name: utsdl-${{ matrix.arch }}-${{ matrix.os }}
          path: utsdl-*.tgz

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: utsdl-*.tgz
          draft: false
          make_latest: true
